services:
  reference-web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped
    container_name: lod-reference-webserver

  gapped-web:
    build:
      context: .
      dockerfile: Dockerfile.gapped
    ports:
      - "8081:80"
    restart: unless-stopped
    container_name: lod-gapped-webserver

